# Generated by Django 5.2.17 on 2026-08-05 12:21

import apps.dockets.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docket_type', models.CharField(choices=[('ambient', 'Ambient'), ('chilled', 'Chilled'), ('returns', 'Returns'), ('transfer', 'Transfer')], db_index=True, max_length=16)),
                ('week_ending', models.DateField(blank=True, db_index=True, null=True)),
                ('docket_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('docket_number', models.CharField(blank=True, max_length=64)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('outgoing_staff_name', models.CharField(blank=True, max_length=120)),
                ('manager_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dockets', to=settings.AUTH_USER_MODEL)),
                ('destination_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='stores.store')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dockets', to='stores.store')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('line_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('docket_number', models.CharField(blank=True, max_length=64)),
                ('amounts', models.JSONField(blank=True, default=dict)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dockets.docket')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.dockets.models.photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dockets.docket')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DocketSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('branch_manager', 'Branch Manager'), ('outgoing_staff', 'Outgoing Staff'), ('outgoing_manager', 'Outgoing Manager'), ('incoming_manager', 'Incoming Manager')], max_length=32)),
                ('signed_name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to=apps.dockets.models.signature_upload_to)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='dockets.docket')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='docket',
            index=models.Index(fields=['store', 'docket_type', '-created_at'], name='dockets_doc_store_i_4b9ea1_idx'),
        ),
        migrations.AddConstraint(
            model_name='docketsignature',
            constraint=models.UniqueConstraint(fields=('docket', 'role'), name='unique_signature_per_role'),
        ),
    ]
