# Generated by Django 5.2.17 on 2026-08-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_code',
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Home store — pre-selected on new dockets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stores.store'),
        ),
    ]
