# Generated by Django 5.2.17 on 2026-08-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_store_code_user_store'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Trading department they work in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='departments.department'),
        ),
    ]
