# Generated by Django 5.2.17 on 2026-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_department_per_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Euro per hour. Blank means the national minimum wage.', max_digits=6, null=True),
        ),
    ]
