# Generated by Django 5.2.17 on 2026-08-06 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_seed_departments'),
        ('stores', '0002_seed_stores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.CreateModel(
            name='StoreDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off for a branch that does not run this department.')),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_departments', to='departments.department')),
                ('manager', models.ForeignKey(blank=True, help_text='Head of department in this branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_departments_led', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='stores.store')),
            ],
            options={
                'ordering': ('department__name', 'store__name'),
                'constraints': [models.UniqueConstraint(fields=('department', 'store'), name='unique_department_per_store')],
            },
        ),
    ]
