# Generated by Django 5.2.17 on 2026-08-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_open_departments_in_every_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedepartment',
            name='is_active',
        ),
    ]
